### ISSUE TITLE
tslint.yaml anchor expand treated as rule

### ISSUE THREAD

**Issue by dmi3y** [palantir/tslint#3821]
### Bug Report

- __TSLint version__:  tslint@5.9.1
- __TypeScript version__: typescript@2.4.2
- __Running TSLint via__:  CLI

I'm trying to leverage yaml anchors for common settings in between ts and js lint rules, and encounter following error:

```
zzzz[~/../../../zzzz/client/ (develop *% u=)]$ yarn lint_tsjs
yarn run v1.5.1
$ tslint -c tslint.yml "!(node_modules)/**/*.js?(x)"

Could not find implementations for the following rules specified in the configuration:
    <<
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
```
I tested `js-yaml@3.7.0` and it will expand `tslint.yaml` into json as expected, so I assume it is happen sometime before converting config file to json. Would be nice to have yaml anchors support in such use cases.

with `tslint.yaml` configuration:

```yaml
defaultSeverity: error
linterOptions:
  exclude:
    - "coverage/**/*"
    - "dist/**/*"
    - "config/utils/**/*.js"
    - "src/common/components/forms/**/*.js"
    - "**/mockData.js"
    - "**/reactCountDownTimer/**/*.js"
extends:
  - tslint:recommended
  - tslint-react
rules: &TS_RULES
  semicolon:
    - true
    - never
  quotemark:
    - true
    - single
    - jsx-double
  indent:
    - true
    - spaces
    - 2
  ordered-imports: false
  interface-name: false
  member-access: false
  object-literal-sort-keys: false
  trailing-comma: false
  space-before-function-paren: true
  arrow-parens: false
  jsx-no-lambda: true
jsRules:
  # common rules with ts
  <<: *TS_RULES
  # semicolon:
  #   - true
  #   - never
  # quotemark:
  #   - true
  #   - single
  #   - jsx-double
  # indent:
  #   - true
  #   - spaces
  #   - 2
  # ordered-imports: false
  # interface-name: false
  # member-access: false
  # object-literal-sort-keys: false
  # trailing-comma: false
  # space-before-function-paren: true
  # arrow-parens: false
  # jsx-no-lambda: true
  # specific rules for js
  jsdoc-format: false
  curly:
    - true
    - ignore-same-line
  max-line-length:
    - true
    - 180
rulesDirectory: []
```

#### Actual behavior
```
zzzz[~/../../../zzzz/client/ (develop *% u=)]$ yarn lint_tsjs
yarn run v1.5.1
$ tslint -c tslint.yml "!(node_modules)/**/*.js?(x)"

Could not find implementations for the following rules specified in the configuration:
    <<
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
```

#### Expected behavior
anchor expended to the actual rules before validation kicks in

Thank you
