### ISSUE TITLE
[Feature Request] Support pattern matching for rule "file-name-casing"

### ISSUE THREAD

**Issue by Ky6uk** [palantir/tslint#4071]
### Feature request

Many projects can have different styles for naming files. For example React projects can have `pascal-case` rule for component files (`Component.tsx`, `Some/Other/Component.tsx`) and `kebab-case` rule for other files (`utils/formatter.ts`, `helper/check-string.ts`).

So I think we should extend rule `file-name-casing` to array of styles with filename pattern as one of arguments. For example: 

```yaml
file-name-casing:
  severity: 'error'
  options:
    - [/\.tsx$/, 'pascal-case']
    - [/\.style\.ts$/, 'pascal-case']
    - [/\.ts$/, 'kebab-case']
```
